### ISSUE TITLE
TODO10/10 Streaming Api

### ISSUE THREAD

**Issue by AprilSuna** [AprilSuna/TwitterDashboard#27]
Using Streaming Api listen to users:

1. Whether they mute someone (add to our training data)
2. Whether they have new reply (if had --> using our training model detective --> give score to certain user)

**Comment by shakingkelly** [comment]
tried account activity api with ngrok
atm there's a webhook connected (from the python repo)
`python3 example-scripts/create-webhook.py
kellyhook https://54b74492.ngrok.io/webhook
200
[{"id":"1183807718034939906","url":"https://54b74492.ngrok.io/webhook","valid":true,"created_timestamp":"2019-10-14 18:12:08 +0000"}]`
cannot use ngrok to tunnel anymore, dunno why, so fail to delete the webhook and do further testing
but i dunno how to thread and conveniently start/stop webhook anyway, so im thinking **continuing with streaming api** (and yiqing didn't seem to use aa api either)

**Comment by shakingkelly** [comment]
regenerated keys haven't been updated

**Comment by shakingkelly** [comment]
reverse to streaming api (hooray)
but need to periodically update mute list
